name: flutter_img_to_pdf
description: A new Flutter project.



publish_to: "none" 













version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"







dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  google_fonts: ^3.0.1
  image_picker: ^0.8.6
  intl: ^0.17.0
  lottie: ^2.2.0
  open_filex: ^4.3.2
  path_provider: ^2.0.10
  pdf: ^3.8.4
  permission_handler: ^10.2.0
  riverpod: ^2.1.1
  share_plus: ^6.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter




flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/json/
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
