name: flutter_img_to_pdf
description: A new Flutter project.

publish_to: "none"

version: 2.0.0+2

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.1.17
  flutter_riverpod: ^2.1.1
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.1.2
  open_filex: ^4.3.2
  path_provider: ^2.0.10
  pdf: ^3.11.0
  permission_handler: ^11.3.1
  rename: ^3.0.2
  riverpod: ^2.1.1
  share_plus: ^9.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: assets/splash.png
  color: "#f2f2f2"

flutter_icons:
  android: true
  image_path: "assets/logo.png"
  adaptive_icon_foreground: "assets/logo_foreground.png"
  adaptive_icon_background: "#ffffff"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
